#!/usr/bin/env python3
"""
LLVM Energy Report Visualizer

Reads energy_report.json (generated by EnergyPass) and produces:
  1. Per-function bar charts (block name vs. energy)
  2. Optional HTML report with embedded charts

Usage:
  python visualize_energy.py                          # uses default path
  python visualize_energy.py path/to/report.json      # custom path
  python visualize_energy.py --html                   # also generate HTML
"""

import json
import sys
import os
from collections import OrderedDict

# ---------------------------------------------------------------------------
# Optional imports – print a friendly message if matplotlib is missing.
# ---------------------------------------------------------------------------
try:
    import matplotlib
    matplotlib.use("Agg")  # non-interactive backend (no GUI needed)
    import matplotlib.pyplot as plt
except ImportError:
    print("matplotlib is required for plotting.")
    print("Install it with:  pip install matplotlib")
    sys.exit(1)


# ---------------------------------------------------------------------------
# 1. Load the JSON report
# ---------------------------------------------------------------------------
def load_report(path="reports/energy_report.json"):
    """Read and parse the JSON energy report."""
    if not os.path.exists(path):
        print(f"[ERROR] Report not found at: {path}")
        print("Make sure EnergyPass ran and generated the file.")
        sys.exit(1)

    with open(path, "r") as f:
        data = json.load(f)

    # Navigate to the function list.
    # JSON structure: {"report": {"functions": [...]}}
    try:
        functions = data["report"]["functions"]
    except KeyError:
        print("[ERROR] Invalid report format: missing 'report' → 'functions'")
        sys.exit(1)

    return functions


# ---------------------------------------------------------------------------
# 2. Plot a bar chart for one function
# ---------------------------------------------------------------------------
def plot_function(func, output_dir="charts"):
    """
    Create a bar chart of block-wise energy for a single function.
    Saves the figure as a PNG file and returns the file path.
    """
    name = func["name"]
    blocks = func["blocks"]

    # Extract data from each block entry.
    block_names = [b["name"] for b in blocks]
    block_energy = [b["energy"] for b in blocks]

    # --------------------------------------------------
    # Create the figure
    # --------------------------------------------------
    fig, ax = plt.subplots(figsize=(max(6, len(blocks) * 1.2), 4.5))

    # Bar positions and colours.
    x_pos = range(len(blocks))
    colours = plt.cm.Blues([0.4 + 0.5 * (e / max(block_energy))
                            if max(block_energy) > 0 else 0.5
                            for e in block_energy])

    bars = ax.bar(x_pos, block_energy, color=colours, edgecolor="navy", linewidth=0.8)

    # --------------------------------------------------
    # Labels, title, and grid
    # --------------------------------------------------
    ax.set_xlabel("Basic Block", fontsize=11, fontweight="bold")
    ax.set_ylabel("Energy (normalized units)", fontsize=11, fontweight="bold")
    ax.set_title(f"Block-wise Energy — {name}", fontsize=13, fontweight="bold")

    ax.set_xticks(x_pos)
    ax.set_xticklabels(block_names, rotation=25, ha="right", fontsize=9)
    ax.yaxis.set_major_formatter(plt.FormatStrFormatter("%.1f"))
    ax.grid(axis="y", linestyle="--", alpha=0.5)
    ax.set_axisbelow(True)

    # Annotate each bar with its value.
    for bar, val in zip(bars, block_energy):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.02 * max(block_energy or [1]),
                f"{val:.2f}", ha="center", va="bottom", fontsize=8, fontweight="bold")

    # --------------------------------------------------
    # Save
    # --------------------------------------------------
    os.makedirs(output_dir, exist_ok=True)
    safe_name = name.replace(" ", "_").replace("/", "_")
    out_path = os.path.join(output_dir, f"{safe_name}_energy.png")
    plt.tight_layout()
    plt.savefig(out_path, dpi=150)
    plt.close(fig)

    print(f"  [OK] Chart saved → {out_path}")
    return out_path


# ---------------------------------------------------------------------------
# 3. Generate an HTML report (optional)
# ---------------------------------------------------------------------------
def generate_html(functions, chart_paths, output_path="reports/energy_report.html"):
    """Create a standalone HTML page embedding all the charts."""
    html_parts = [
        "<!DOCTYPE html>",
        "<html lang='en'><head><meta charset='utf-8'>",
        "<title>LLVM Energy Report</title>",
        "<style>",
        "  body { font-family: -apple-system, sans-serif; max-width: 960px; margin: 2em auto; padding: 0 1em; background: #fafafa; }",
        "  h1 { color: #1a1a2e; border-bottom: 3px solid #1a1a2e; padding-bottom: 0.3em; }",
        "  .func-card { background: #fff; border-radius: 8px; box-shadow: 0 2px 6px rgba(0,0,0,0.1); margin: 1.5em 0; padding: 1em; }",
        "  .func-card h2 { margin-top: 0; color: #16213e; }",
        "  table { width: 100%; border-collapse: collapse; margin: 1em 0; }",
        "  th, td { text-align: left; padding: 6px 10px; border-bottom: 1px solid #ddd; }",
        "  th { background: #16213e; color: #fff; }",
        "  img { max-width: 100%; height: auto; display: block; margin: 1em 0; }",
        "  .footer { text-align: center; color: #888; font-size: 0.85em; margin-top: 2em; }",
        "</style></head><body>",
        "<h1>\U0001f4ca LLVM Energy Analysis Report</h1>",
    ]

    for func, chart_path in zip(functions, chart_paths):
        name = func["name"]
        total = func["total_energy"]
        blocks = func["blocks"]

        html_parts.append(f"<div class='func-card'>")
        html_parts.append(f"  <h2>Function: {name}</h2>")
        html_parts.append(f"  <p><strong>Total Energy:</strong> {total:.2f}</p>")
        html_parts.append(f"  <table><tr><th>Block</th><th>Frequency</th><th>Energy</th></tr>")

        for b in blocks:
            html_parts.append(
                f"    <tr><td>{b['name']}</td>"
                f"<td>{b['frequency']:.2f}</td>"
                f"<td>{b['energy']:.2f}</td></tr>"
            )

        html_parts.append("  </table>")

        # Embed chart image as base64 so the HTML is self-contained.
        if os.path.exists(chart_path):
            import base64
            with open(chart_path, "rb") as img_f:
                b64 = base64.b64encode(img_f.read()).decode()
            html_parts.append(f"  <img src='data:image/png;base64,{b64}' "
                              f"alt='Energy chart for {name}'>")

        html_parts.append("</div>")

    html_parts.append("<div class='footer'>Generated by LLVM EnergyPass</div>")
    html_parts.append("</body></html>")

    with open(output_path, "w") as f:
        f.write("\n".join(html_parts))

    print(f"  [OK] HTML report → {output_path}")


# ---------------------------------------------------------------------------
# 4. Main entry point
# ---------------------------------------------------------------------------
def main():
    # Accept optional custom report path from command line.
    report_path = sys.argv[1] if len(sys.argv) > 1 else "reports/energy_report.json"
    generate_html_report = "--html" in sys.argv

    print(f"[*] Loading report: {report_path}")
    functions = load_report(report_path)
    print(f"[*] Found {len(functions)} function(s)\n")

    chart_paths = []
    for func in functions:
        print(f"  Function: {func['name']}  (total energy: {func['total_energy']:.2f})")
        path = plot_function(func)
        chart_paths.append(path)

    if generate_html_report:
        print("\n[*] Generating HTML report ...")
        generate_html(functions, chart_paths)

    print("\n[Done]")


if __name__ == "__main__":
    main()
